=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'date'

module Rapid7VmConsole
  # 
  class AssetPolicy
    # The name of the policy's benchmark.
    attr_accessor :benchmark_name

    # The version number of the benchmark that includes the policy.
    attr_accessor :benchmark_version

    # A grouping of similar benchmarks based on their source, purpose, or other criteria. Examples include FDCC, USGCB, and CIS.
    attr_accessor :category

    # The description of the policy.
    attr_accessor :description

    # The number of assets that are not compliant with the policy. The assets considered in the calculation are based on the user's list of accessible assets.
    attr_accessor :failed_assets_count

    # The number of rules in the policy that are not compliant with any scanned assets. The assets considered in the calculation are based on the user's list of accessible assets.
    attr_accessor :failed_rules_count

    # The textual representation of the policy identifier.
    attr_accessor :id

    # A flag indicating whether the policy is custom.
    attr_accessor :is_custom

    # Hypermedia links to corresponding or related resources.
    attr_accessor :links

    # The number of assets that were attempted to be scanned, but are not applicable to the policy. The assets considered in the calculation are based on the user's list of accessible assets.
    attr_accessor :not_applicable_assets_count

    # The number of rules in the policy that are not applicable with any scanned assets. The assets considered in the calculation are based on the user's list of accessible assets.
    attr_accessor :not_applicable_rules_count

    # The number of assets that are compliant with the policy. The assets considered in the calculation are based on the user's list of accessible assets.
    attr_accessor :passed_assets_count

    # The number of rules in the policy that are compliant with all scanned assets. The assets considered in the calculation are based on the user's list of accessible assets.
    attr_accessor :passed_rules_count

    # The name of the policy.
    attr_accessor :policy_name

    # The ratio of PASS results for the rules to the total number of rules in each policy.
    attr_accessor :rule_compliance

    # The change in rule compliance between the last two scans of all assets. The list of scanned policies is based on the user's list of accessible assets.
    attr_accessor :rule_compliance_delta

    # The textual representation of the policy scope. Policies that are automatically available have `\"Built-in\"` scope, whereas policies created by users have scope as `\"Custom\"`.
    attr_accessor :scope

    # The overall compliance status of the policy.
    attr_accessor :status

    # The identifier of the policy
    attr_accessor :surrogate_id

    # The title of the policy as visible to the user.
    attr_accessor :title

    # The number of rules defined in the policy with a role of \"unscored\". These rules will not affect rule compliance scoring for the policy.
    attr_accessor :unscored_rules

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'benchmark_name' => :'benchmarkName',
        :'benchmark_version' => :'benchmarkVersion',
        :'category' => :'category',
        :'description' => :'description',
        :'failed_assets_count' => :'failedAssetsCount',
        :'failed_rules_count' => :'failedRulesCount',
        :'id' => :'id',
        :'is_custom' => :'isCustom',
        :'links' => :'links',
        :'not_applicable_assets_count' => :'notApplicableAssetsCount',
        :'not_applicable_rules_count' => :'notApplicableRulesCount',
        :'passed_assets_count' => :'passedAssetsCount',
        :'passed_rules_count' => :'passedRulesCount',
        :'policy_name' => :'policyName',
        :'rule_compliance' => :'ruleCompliance',
        :'rule_compliance_delta' => :'ruleComplianceDelta',
        :'scope' => :'scope',
        :'status' => :'status',
        :'surrogate_id' => :'surrogateId',
        :'title' => :'title',
        :'unscored_rules' => :'unscoredRules'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'benchmark_name' => :'String',
        :'benchmark_version' => :'String',
        :'category' => :'String',
        :'description' => :'String',
        :'failed_assets_count' => :'Integer',
        :'failed_rules_count' => :'Integer',
        :'id' => :'String',
        :'is_custom' => :'BOOLEAN',
        :'links' => :'Array<Link>',
        :'not_applicable_assets_count' => :'Integer',
        :'not_applicable_rules_count' => :'Integer',
        :'passed_assets_count' => :'Integer',
        :'passed_rules_count' => :'Integer',
        :'policy_name' => :'String',
        :'rule_compliance' => :'Float',
        :'rule_compliance_delta' => :'Float',
        :'scope' => :'String',
        :'status' => :'String',
        :'surrogate_id' => :'Integer',
        :'title' => :'String',
        :'unscored_rules' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'benchmarkName')
        self.benchmark_name = attributes[:'benchmarkName']
      end

      if attributes.has_key?(:'benchmarkVersion')
        self.benchmark_version = attributes[:'benchmarkVersion']
      end

      if attributes.has_key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'failedAssetsCount')
        self.failed_assets_count = attributes[:'failedAssetsCount']
      end

      if attributes.has_key?(:'failedRulesCount')
        self.failed_rules_count = attributes[:'failedRulesCount']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'isCustom')
        self.is_custom = attributes[:'isCustom']
      end

      if attributes.has_key?(:'links')
        if (value = attributes[:'links']).is_a?(Array)
          self.links = value
        end
      end

      if attributes.has_key?(:'notApplicableAssetsCount')
        self.not_applicable_assets_count = attributes[:'notApplicableAssetsCount']
      end

      if attributes.has_key?(:'notApplicableRulesCount')
        self.not_applicable_rules_count = attributes[:'notApplicableRulesCount']
      end

      if attributes.has_key?(:'passedAssetsCount')
        self.passed_assets_count = attributes[:'passedAssetsCount']
      end

      if attributes.has_key?(:'passedRulesCount')
        self.passed_rules_count = attributes[:'passedRulesCount']
      end

      if attributes.has_key?(:'policyName')
        self.policy_name = attributes[:'policyName']
      end

      if attributes.has_key?(:'ruleCompliance')
        self.rule_compliance = attributes[:'ruleCompliance']
      end

      if attributes.has_key?(:'ruleComplianceDelta')
        self.rule_compliance_delta = attributes[:'ruleComplianceDelta']
      end

      if attributes.has_key?(:'scope')
        self.scope = attributes[:'scope']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'surrogateId')
        self.surrogate_id = attributes[:'surrogateId']
      end

      if attributes.has_key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.has_key?(:'unscoredRules')
        self.unscored_rules = attributes[:'unscoredRules']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      status_validator = EnumAttributeValidator.new('String', ['PASS', 'FAIL', 'NOT_APPLICABLE'])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ['PASS', 'FAIL', 'NOT_APPLICABLE'])
      unless validator.valid?(status)
        fail ArgumentError, 'invalid value for "status", must be one of #{validator.allowable_values}.'
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          benchmark_name == o.benchmark_name &&
          benchmark_version == o.benchmark_version &&
          category == o.category &&
          description == o.description &&
          failed_assets_count == o.failed_assets_count &&
          failed_rules_count == o.failed_rules_count &&
          id == o.id &&
          is_custom == o.is_custom &&
          links == o.links &&
          not_applicable_assets_count == o.not_applicable_assets_count &&
          not_applicable_rules_count == o.not_applicable_rules_count &&
          passed_assets_count == o.passed_assets_count &&
          passed_rules_count == o.passed_rules_count &&
          policy_name == o.policy_name &&
          rule_compliance == o.rule_compliance &&
          rule_compliance_delta == o.rule_compliance_delta &&
          scope == o.scope &&
          status == o.status &&
          surrogate_id == o.surrogate_id &&
          title == o.title &&
          unscored_rules == o.unscored_rules
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [benchmark_name, benchmark_version, category, description, failed_assets_count, failed_rules_count, id, is_custom, links, not_applicable_assets_count, not_applicable_rules_count, passed_assets_count, passed_rules_count, policy_name, rule_compliance, rule_compliance_delta, scope, status, surrogate_id, title, unscored_rules].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Rapid7VmConsole.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
