=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'date'

module Rapid7VmConsole
  # 
  class ScanTemplateWebSpider
    # Whether scanning of multi-use devices, such as printers or print servers should be avoided.
    attr_accessor :dont_scan_multi_use_devices

    # Whether query strings are using in URLs when web spidering. This causes the web spider to make many more requests to the Web server. This will increase overall scan time and possibly affect the Web server's performance for legitimate users.
    attr_accessor :include_query_strings

    # Paths to use when web spidering.
    attr_accessor :paths

    # Patterns to match responses during web spidering.
    attr_accessor :patterns

    # Performance settings used during web spidering.
    attr_accessor :performance

    # Whether to determine if discovered logon forms accept commonly used user names or passwords. The process may cause authentication services with certain security policies to lock out accounts with these credentials.
    attr_accessor :test_common_usernames_and_passwords

    # Whether to test for persistent cross-site scripting during a single scan. This test helps to reduce the risk of dangerous attacks via malicious code stored on Web servers. Enabling it may increase Web spider scan times.
    attr_accessor :test_xss_in_single_scan

    # The `User-Agent` to use when web spidering. Defaults to `\"Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727)\"`.
    attr_accessor :user_agent

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'dont_scan_multi_use_devices' => :'dontScanMultiUseDevices',
        :'include_query_strings' => :'includeQueryStrings',
        :'paths' => :'paths',
        :'patterns' => :'patterns',
        :'performance' => :'performance',
        :'test_common_usernames_and_passwords' => :'testCommonUsernamesAndPasswords',
        :'test_xss_in_single_scan' => :'testXssInSingleScan',
        :'user_agent' => :'userAgent'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'dont_scan_multi_use_devices' => :'BOOLEAN',
        :'include_query_strings' => :'BOOLEAN',
        :'paths' => :'ScanTemplateWebSpiderPaths',
        :'patterns' => :'ScanTemplateWebSpiderPatterns',
        :'performance' => :'ScanTemplateWebSpiderPerformance',
        :'test_common_usernames_and_passwords' => :'BOOLEAN',
        :'test_xss_in_single_scan' => :'BOOLEAN',
        :'user_agent' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'dontScanMultiUseDevices')
        self.dont_scan_multi_use_devices = attributes[:'dontScanMultiUseDevices']
      end

      if attributes.has_key?(:'includeQueryStrings')
        self.include_query_strings = attributes[:'includeQueryStrings']
      end

      if attributes.has_key?(:'paths')
        self.paths = attributes[:'paths']
      end

      if attributes.has_key?(:'patterns')
        self.patterns = attributes[:'patterns']
      end

      if attributes.has_key?(:'performance')
        self.performance = attributes[:'performance']
      end

      if attributes.has_key?(:'testCommonUsernamesAndPasswords')
        self.test_common_usernames_and_passwords = attributes[:'testCommonUsernamesAndPasswords']
      end

      if attributes.has_key?(:'testXssInSingleScan')
        self.test_xss_in_single_scan = attributes[:'testXssInSingleScan']
      end

      if attributes.has_key?(:'userAgent')
        self.user_agent = attributes[:'userAgent']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          dont_scan_multi_use_devices == o.dont_scan_multi_use_devices &&
          include_query_strings == o.include_query_strings &&
          paths == o.paths &&
          patterns == o.patterns &&
          performance == o.performance &&
          test_common_usernames_and_passwords == o.test_common_usernames_and_passwords &&
          test_xss_in_single_scan == o.test_xss_in_single_scan &&
          user_agent == o.user_agent
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [dont_scan_multi_use_devices, include_query_strings, paths, patterns, performance, test_common_usernames_and_passwords, test_xss_in_single_scan, user_agent].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Rapid7VmConsole.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
