=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Rapid7VmConsole::AssetDiscoveryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AssetDiscoveryApi' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::AssetDiscoveryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetDiscoveryApi' do
    it 'should create an instance of AssetDiscoveryApi' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::AssetDiscoveryApi)
    end
  end

  # unit tests for create_sonar_query
  # Sonar Queries
  # Creates a sonar query.
  # @param [Hash] opts the optional parameters
  # @option opts [SonarQuery] :query The criteria for a Sonar query.
  # @return [CreatedReferenceDiscoveryQueryIDLink]
  describe 'create_sonar_query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_sonar_query
  # Sonar Query
  # Removes a sonar query.
  # @param id The identifier of the Sonar query.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_sonar_query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_discovery_connection
  # Discovery Connection
  # Returns a discovery connection.
  # @param id The identifier of the discovery connection.
  # @param [Hash] opts the optional parameters
  # @return [DiscoveryConnection]
  describe 'get_discovery_connection test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_discovery_connections
  # Discovery Connections
  # Returns all discovery connections.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The index of the page (zero-based) to retrieve.
  # @option opts [Integer] :size The number of records per page to retrieve.
  # @option opts [Array<String>] :sort The criteria to sort the records by, in the format: &#x60;property[,ASC|DESC]&#x60;. The default sort order is ascending. Multiple sort criteria can be specified using multiple sort query parameters.
  # @return [PageOfDiscoveryConnection]
  describe 'get_discovery_connections test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sonar_queries
  # Sonar Queries
  # Returns all sonar queries.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesSonarQuery]
  describe 'get_sonar_queries test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sonar_query
  # Sonar Query
  # Returns a sonar query.
  # @param id The identifier of the Sonar query.
  # @param [Hash] opts the optional parameters
  # @return [SonarQuery]
  describe 'get_sonar_query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sonar_query_assets
  # Sonar Query Assets
  # Returns the assets that are discovered by a Sonar query.
  # @param id The identifier of the Sonar query.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesDiscoveryAsset]
  describe 'get_sonar_query_assets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reconnect_discovery_connection
  # Discovery Connection Reconnect
  # Attempts to reconnect the discovery connection.
  # @param id The identifier of the discovery connection.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'reconnect_discovery_connection test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sonar_query_search
  # Sonar Query Search
  # Executes a Sonar query to discover assets with the given search criteria.
  # @param [Hash] opts the optional parameters
  # @option opts [SonarCriteria] :query The criteria for a Sonar query.
  # @return [Array<DiscoveryAsset>]
  describe 'sonar_query_search test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_sonar_query
  # Sonar Query
  # Updates a sonar query.
  # @param id The identifier of the Sonar query.
  # @param [Hash] opts the optional parameters
  # @option opts [SonarQuery] :query The criteria for a Sonar query.
  # @return [Links]
  describe 'update_sonar_query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
