=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Rapid7VmConsole::CredentialApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CredentialApi' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::CredentialApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CredentialApi' do
    it 'should create an instance of CredentialApi' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::CredentialApi)
    end
  end

  # unit tests for create_shared_credential
  # Shared Credentials
  # Creates a new shared credential.
  # @param [Hash] opts the optional parameters
  # @option opts [SharedCredential] :credential The specification of a shared credential.
  # @return [CreatedReferenceCredentialIDLink]
  describe 'create_shared_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_all_shared_credentials
  # Shared Credentials
  # Deletes all shared credentials.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_all_shared_credentials test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_shared_credential
  # Shared Credential
  # Deletes the specified shared scan credential.
  # @param id The identifier of the credential.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_shared_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_shared_credential
  # Shared Credential
  # Retrieves the specified shared credential.
  # @param id The identifier of the credential.
  # @param [Hash] opts the optional parameters
  # @return [SharedCredential]
  describe 'get_shared_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_shared_credentials
  # Shared Credentials
  # Retrieves all defined shared credential resources.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesSharedCredential]
  describe 'get_shared_credentials test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_shared_credential
  # Shared Credential
  # Updates the specified shared credential.
  # @param id The identifier of the credential.
  # @param [Hash] opts the optional parameters
  # @option opts [SharedCredential] :credential The specification of the shared credential to update.
  # @return [Links]
  describe 'update_shared_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
