=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Rapid7VmConsole::RemediationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RemediationApi' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::RemediationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RemediationApi' do
    it 'should create an instance of RemediationApi' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::RemediationApi)
    end
  end

  # unit tests for get_asset_vulnerability_solutions
  # Asset Vulnerability Solution
  # Returns the highest-superceding rollup solutions for a vulnerability on an asset. The solution(s) selected will be the most recent and cost-effective means by which the vulnerability can be remediated.
  # @param id The identifier of the asset.
  # @param vulnerability_id The identifier of the vulnerability.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesMatchedSolution]
  describe 'get_asset_vulnerability_solutions test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
