=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Rapid7VmConsole::ScanApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScanApi' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::ScanApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScanApi' do
    it 'should create an instance of ScanApi' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::ScanApi)
    end
  end

  # unit tests for get_scan
  # Scan
  # Returns the specified scan.
  # @param id The identifier of the scan.
  # @param [Hash] opts the optional parameters
  # @return [Scan]
  describe 'get_scan test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_scans
  # Scans
  # Returns all scans.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :active Return running scans or past scans (true/false value).
  # @option opts [Integer] :page The index of the page (zero-based) to retrieve.
  # @option opts [Integer] :size The number of records per page to retrieve.
  # @option opts [Array<String>] :sort The criteria to sort the records by, in the format: &#x60;property[,ASC|DESC]&#x60;. The default sort order is ascending. Multiple sort criteria can be specified using multiple sort query parameters.
  # @return [PageOfGlobalScan]
  describe 'get_scans test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_scans
  # Site Scans
  # Returns the scans for the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :active Return running scans or past scans (true/false value).
  # @option opts [Integer] :page The index of the page (zero-based) to retrieve.
  # @option opts [Integer] :size The number of records per page to retrieve.
  # @option opts [Array<String>] :sort The criteria to sort the records by, in the format: &#x60;property[,ASC|DESC]&#x60;. The default sort order is ascending. Multiple sort criteria can be specified using multiple sort query parameters.
  # @return [PageOfScan]
  describe 'get_site_scans test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_scan_status
  # Scan Status
  # Updates the scan status. Can pause, resume, and stop scans using this resource. In order to stop a scan the scan must be running or paused. In order to resume a scan the scan must be paused. In order to pause a scan the scan must be running.
  # @param id The identifier of the scan.
  # @param status The status of the scan.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'set_scan_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for start_scan
  # Site Scans
  # Starts a scan for the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [AdhocScan] :scan The details for the scan.
  # @return [CreatedReferenceScanIDLink]
  describe 'start_scan test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
