=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Rapid7VmConsole::SiteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SiteApi' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::SiteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SiteApi' do
    it 'should create an instance of SiteApi' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::SiteApi)
    end
  end

  # unit tests for add_site_tag
  # Site Tag
  # Adds a tag to the site.
  # @param id The identifier of the site.
  # @param tag_id The identifier of the tag.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'add_site_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for add_site_user
  # Site Users Access
  # Grants a non-administrator user access to the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :param0 The identifier of the user.
  # @return [ReferenceWithUserIDLink]
  describe 'add_site_user test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_site
  # Sites
  # Creates a new site with the specified configuration.
  # @param [Hash] opts the optional parameters
  # @option opts [SiteCreateResource] :site Resource for creating a site configuration.
  # @return [ReferenceWithSiteIDLink]
  describe 'create_site test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_site_credential
  # Site Scan Credentials
  # Creates a new site credential.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [SiteCredential] :site_credential The specification of a site credential.
  # @return [CreatedReferenceCredentialIDLink]
  describe 'create_site_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_site_scan_schedule
  # Site Scan Schedules
  # Creates a new scan schedule for the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [ScanSchedule] :scan_schedule Resource for a scan schedule.
  # @return [ReferenceWithScanScheduleIDLink]
  describe 'create_site_scan_schedule test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_site_smtp_alert
  # Site SMTP Alerts
  # Creates a new SMTP alert for the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [SmtpAlert] :alert Resource for creating a new SMTP alert.
  # @return [ReferenceWithAlertIDLink]
  describe 'create_site_smtp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_site_snmp_alert
  # Site SNMP Alerts
  # Creates a new SNMP alert for the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [SnmpAlert] :alert Resource for creating a new SNMP alert.
  # @return [ReferenceWithAlertIDLink]
  describe 'create_site_snmp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_site_syslog_alert
  # Site Syslog Alerts
  # Creates a new Syslog alert for the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [SyslogAlert] :alert Resource for creating a new Syslog alert.
  # @return [ReferenceWithAlertIDLink]
  describe 'create_site_syslog_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_all_site_alerts
  # Site Alerts
  # Deletes all alerts from the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_all_site_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_all_site_credentials
  # Site Scan Credentials
  # Deletes all site credentials from the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_all_site_credentials test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_all_site_scan_schedules
  # Site Scan Schedules
  # Deletes all scan schedules from the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_all_site_scan_schedules test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_all_site_smtp_alerts
  # Site SMTP Alerts
  # Deletes all SMTP alerts from the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_all_site_smtp_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_all_site_snmp_alerts
  # Site SNMP Alerts
  # Deletes all SNMP alerts from the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_all_site_snmp_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_all_site_syslog_alerts
  # Site Syslog Alerts
  # Deletes all Syslog alerts from the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_all_site_syslog_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_site
  # Site
  # site.delete.description
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_site test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_site_credential
  # Site Scan Credential
  # Deletes the specified site credential.
  # @param id The identifier of the site.
  # @param credential_id The identifier of the site credential.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_site_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_site_scan_schedule
  # Site Scan Schedule
  # Deletes the specified scan schedule from the site.
  # @param id The identifier of the site.
  # @param schedule_id The identifier of the scan schedule.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_site_scan_schedule test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_site_smtp_alert
  # Site SMTP Alert
  # Deletes the specified SMTP alert from the site.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_site_smtp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_site_snmp_alert
  # Site SNMP Alert
  # Deletes the specified SNMP alert from the site.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_site_snmp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_site_syslog_alert
  # Site Syslog Alert
  # Deletes the specified Syslog alert from the site.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'delete_site_syslog_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for enable_shared_credential_on_site
  # Assigned Shared Credential Enablement
  # Enable or disable the shared credential for the site&#39;s scans.
  # @param id The identifier of the site.
  # @param credential_id The identifier of the shared credential.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :status Flag indicating whether the shared credential is enabled for the site&#39;s scans.
  # @return [Links]
  describe 'enable_shared_credential_on_site test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for enable_site_credential
  # Site Credential Enablement
  # Enable or disable the site credential for scans.
  # @param id The identifier of the site.
  # @param credential_id The identifier of the site credential.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :status Flag indicating whether the credential is enabled for use during the scan.
  # @return [Links]
  describe 'enable_site_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_excluded_asset_groups
  # Site Excluded Asset Groups
  # Retrieves the excluded asset groups in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesAssetGroup]
  describe 'get_excluded_asset_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_excluded_targets
  # Site Excluded Targets
  # Retrieves the excluded targets in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ScanTargetsResource]
  describe 'get_excluded_targets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_included_asset_groups
  # Site Included Asset Groups
  # Retrieves the included asset groups in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesAssetGroup]
  describe 'get_included_asset_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_included_targets
  # Site Included Targets
  # Retrieves the included targets in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ScanTargetsResource]
  describe 'get_included_targets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site
  # Site
  # Retrieves the site with the specified identifier.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'get_site test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_alerts
  # Site Alerts
  # Retrieve all alerts defined in the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesAlert]
  describe 'get_site_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_assets
  # Site Assets
  # Retrieves a paged resource of assets linked with the specified site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The index of the page (zero-based) to retrieve.
  # @option opts [Integer] :size The number of records per page to retrieve.
  # @option opts [Array<String>] :sort The criteria to sort the records by, in the format: &#x60;property[,ASC|DESC]&#x60;. The default sort order is ascending. Multiple sort criteria can be specified using multiple sort query parameters.
  # @return [PageOfAsset]
  describe 'get_site_assets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_credential
  # Site Scan Credential
  # Retrieves the specified site credential.
  # @param id The identifier of the site.
  # @param credential_id The identifier of the site credential.
  # @param [Hash] opts the optional parameters
  # @return [SiteCredential]
  describe 'get_site_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_credentials
  # Site Scan Credentials
  # Retrieves all defined site credential resources.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesSiteCredential]
  describe 'get_site_credentials test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_discovery_connection
  # Site Discovery Connection
  # Retrieves the discovery connection assigned to the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [SiteDiscoveryConnection]
  describe 'get_site_discovery_connection test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_discovery_search_criteria
  # Site Discovery Search Criteria
  # Retrieve the search criteria of the dynamic site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [DiscoverySearchCriteria]
  describe 'get_site_discovery_search_criteria test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_organization
  # Site Organization Information
  # Retrieves the site organization information.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [SiteOrganization]
  describe 'get_site_organization test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_scan_engine
  # Site Scan Engine
  # Retrieves the resource of the scan engine assigned to the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ScanEngine]
  describe 'get_site_scan_engine test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_scan_schedule
  # Site Scan Schedule
  # Retrieves the specified scan schedule.
  # @param id The identifier of the site.
  # @param schedule_id The identifier of the scan schedule.
  # @param [Hash] opts the optional parameters
  # @return [ScanSchedule]
  describe 'get_site_scan_schedule test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_scan_schedules
  # Site Scan Schedules
  # Returns all scan schedules for the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesScanSchedule]
  describe 'get_site_scan_schedules test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_scan_template
  # Site Scan Template
  # Retrieves the resource of the scan template assigned to the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ScanTemplate]
  describe 'get_site_scan_template test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_shared_credentials
  # Assigned Shared Credentials
  # Retrieve all of the shared credentials assigned to the site. These shared credentials can be enabled/disabled for the site&#39;s scan.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesSiteSharedCredential]
  describe 'get_site_shared_credentials test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_smtp_alert
  # Site SMTP Alert
  # Retrieves the specified SMTP alert.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @return [SmtpAlert]
  describe 'get_site_smtp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_smtp_alerts
  # Site SMTP Alerts
  # Retrieves all SMTP alerts defined in the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesSmtpAlert]
  describe 'get_site_smtp_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_snmp_alert
  # Site SNMP Alert
  # Retrieves the specified SNMP alert.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @return [SnmpAlert]
  describe 'get_site_snmp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_snmp_alerts
  # Site SNMP Alerts
  # Retrieves all SNMP alerts defined in the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesSnmpAlert]
  describe 'get_site_snmp_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_syslog_alert
  # Site Syslog Alert
  # Retrieves the specified Syslog alert.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @return [SyslogAlert]
  describe 'get_site_syslog_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_syslog_alerts
  # Site Syslog Alerts
  # Retrieves all Syslog alerts defined in the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesSyslogAlert]
  describe 'get_site_syslog_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_tags
  # Site Tags
  # Retrieves the list of tags added to the sites.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesTag]
  describe 'get_site_tags test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_site_users
  # Site Users Access
  # Retrieve the list of non-administrator users that have access to the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesUser]
  describe 'get_site_users test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sites
  # Sites
  # Retrieves a paged resource of accessible sites.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The index of the page (zero-based) to retrieve.
  # @option opts [Integer] :size The number of records per page to retrieve.
  # @option opts [Array<String>] :sort The criteria to sort the records by, in the format: &#x60;property[,ASC|DESC]&#x60;. The default sort order is ascending. Multiple sort criteria can be specified using multiple sort query parameters.
  # @return [PageOfSite]
  describe 'get_sites test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_web_auth_html_forms
  # Web Authentication HTML Forms
  # Retrieves all HTML form authentications configured in the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesWebFormAuthentication]
  describe 'get_web_auth_html_forms test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_web_auth_http_headers
  # Web Authentication HTTP Headers
  # Retrieves all HTTP header authentications configured in the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [ResourcesWebHeaderAuthentication]
  describe 'get_web_auth_http_headers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_all_excluded_asset_groups
  # Site Excluded Asset Groups
  # Removes all excluded asset groups from the specified static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_all_excluded_asset_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_all_included_asset_groups
  # Site Included Asset Groups
  # Removes all included asset groups from the specified static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_all_included_asset_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_asset_from_site
  # Site Asset
  # Removes an asset from a site. The asset will only be deleted if it belongs to no other sites.
  # @param id The identifier of the site.
  # @param asset_id The identifier of the asset.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_asset_from_site test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_excluded_asset_group
  # Site Excluded Asset Group
  # Removes the specified asset group from the excluded asset groups configured in the static site.
  # @param id The identifier of the site.
  # @param asset_group_id The identifier of the asset group.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_excluded_asset_group test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_included_asset_group
  # Site Included Asset Group
  # Removes the specified asset group from the included asset groups configured in the static site.
  # @param id The identifier of the site.
  # @param asset_group_id The identifier of the asset group.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_included_asset_group test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_site_assets
  # Site Assets
  # Removes all assets from the specified site. Assets will be deleted entirely from the Security Console if either Asset Linking is disabled or if Asset Linking is enabled and the asset only existed in this site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_site_assets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_site_tag
  # Site Tag
  # Removes the specified tag from the site&#39;s tags.
  # @param id The identifier of the site.
  # @param tag_id The identifier of the tag.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_site_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_site_user
  # Site User Access
  # Removes the specified user from the site&#39;s access list.
  # @param id The identifier of the site.
  # @param user_id The identifier of the user.
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'remove_site_user test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_credentials
  # Site Scan Credentials
  # Updates multiple site credentials.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<SiteCredential>] :site_credentials A list of site credentials resources.
  # @return [Links]
  describe 'set_site_credentials test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_discovery_connection
  # Site Discovery Connection
  # Updates the discovery connection assigned to the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :connection_id The identifier of the discovery connection.
  # @return [Links]
  describe 'set_site_discovery_connection test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_discovery_search_criteria
  # Site Discovery Search Criteria
  # Update the search criteria of the dynamic site.
  # @param id The identifier of the site.
  # @param param1 param1
  # @param [Hash] opts the optional parameters
  # @return [Links]
  describe 'set_site_discovery_search_criteria test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_scan_engine
  # Site Scan Engine
  # Updates the assigned scan engine to the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :scan_engine_id The identifier of the scan engine.
  # @return [Links]
  describe 'set_site_scan_engine test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_scan_schedules
  # Site Scan Schedules
  # Updates all scan schedules for the specified site in a single request using the array of resources defined in the request body.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<ScanSchedule>] :scan_schedules Array of resources for updating all scan schedules defined in the site. Scan schedules defined in the site that are omitted from this request will be deleted from the site.
  # @return [Links]
  describe 'set_site_scan_schedules test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_scan_template
  # Site Scan Template
  # Updates the assigned scan template to the site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :scan_template_id The identifier of the scan template.
  # @return [Links]
  describe 'set_site_scan_template test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_smtp_alerts
  # Site SMTP Alerts
  # Updates all SMTP alerts for the specified site in a single request using the array of resources defined in the request body.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<SmtpAlert>] :alert Array of resources for updating all SMTP alerts defined in the site. Alerts defined in the site that are omitted from this request will be deleted from the site.
  # @return [Links]
  describe 'set_site_smtp_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_snmp_alerts
  # Site SNMP Alerts
  # Updates all SNMP alerts for the specified site in a single request using the array of resources defined in the request body.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<SnmpAlert>] :alert Array of resources for updating all SNMP alerts defined in the site. Alerts defined in the site that are omitted from this request will be deleted from the site.
  # @return [Links]
  describe 'set_site_snmp_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_syslog_alerts
  # Site Syslog Alerts
  # Updates all Syslog alerts for the specified site in a single request using the array of resources defined in the request body.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<SyslogAlert>] :alert Array of resources for updating all Syslog alerts defined in the site. Alerts defined in the site that are omitted from this request will be deleted from the site.
  # @return [Links]
  describe 'set_site_syslog_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_tags
  # Site Tags
  # Updates the site&#39;s list of tags.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Integer>] :tags A list of tag identifiers to replace the site&#39;s tags.
  # @return [Links]
  describe 'set_site_tags test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_site_users
  # Site Users Access
  # Updates the site&#39;s access list.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Integer>] :users A list of user identifiers to replace the site&#39;s access list.
  # @return [Links]
  describe 'set_site_users test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_excluded_asset_groups
  # Site Excluded Asset Groups
  # Updates the excluded asset groups in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Integer>] :asset_group_ids Array of asset group identifiers.
  # @return [Links]
  describe 'update_excluded_asset_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_excluded_targets
  # Site Excluded Targets
  # Updates the excluded targets in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :scan_targets List of addresses to be the site&#39;s new excluded scan targets. Each address is a string that can represent either a hostname, ipv4 address, ipv4 address range, ipv6 address, or CIDR notation.
  # @return [Links]
  describe 'update_excluded_targets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_included_asset_groups
  # Site Included Asset Groups
  # Updates the included asset groups in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Integer>] :asset_group_ids Array of asset group identifiers.
  # @return [Links]
  describe 'update_included_asset_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_included_targets
  # Site Included Targets
  # Updates the included targets in a static site.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :scan_targets List of addresses to be the site&#39;s new included scan targets. Each address is a string that can represent either a hostname, ipv4 address, ipv4 address range, ipv6 address, or CIDR notation.
  # @return [Links]
  describe 'update_included_targets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_site
  # Site
  # Updates the configuration of the site with the specified identifier.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [SiteUpdateResource] :site Resource for updating a site configuration.
  # @return [Links]
  describe 'update_site test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_site_credential
  # Site Scan Credential
  # Updates the specified site credential.
  # @param id The identifier of the site.
  # @param credential_id The identifier of the site credential.
  # @param [Hash] opts the optional parameters
  # @option opts [SiteCredential] :site_credential The specification of the site credential to update.
  # @return [Links]
  describe 'update_site_credential test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_site_organization
  # Site Organization Information
  # Updates the site organization information.
  # @param id The identifier of the site.
  # @param [Hash] opts the optional parameters
  # @option opts [SiteOrganization] :site_organization Resource for updating the specified site&#39;s organization information.
  # @return [Links]
  describe 'update_site_organization test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_site_scan_schedule
  # Site Scan Schedule
  # Updates the specified scan schedule.
  # @param id The identifier of the site.
  # @param schedule_id The identifier of the scan schedule.
  # @param [Hash] opts the optional parameters
  # @option opts [ScanSchedule] :scan_schedule Resource for updating the specified scan schedule.
  # @return [Links]
  describe 'update_site_scan_schedule test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_site_smtp_alert
  # Site SMTP Alert
  # Updates the specified SMTP alert.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @option opts [SmtpAlert] :alert Resource for updating the specified SMTP alert.
  # @return [Links]
  describe 'update_site_smtp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_site_snmp_alert
  # Site SNMP Alert
  # Updates the specified SNMP alert.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @option opts [SnmpAlert] :alert Resource for updating the specified SNMP alert.
  # @return [Links]
  describe 'update_site_snmp_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_site_syslog_alert
  # Site Syslog Alert
  # Updates the specified Syslog alert.
  # @param id The identifier of the site.
  # @param alert_id The identifier of the alert.
  # @param [Hash] opts the optional parameters
  # @option opts [SyslogAlert] :alert Resource for updating the specified Syslog alert.
  # @return [Links]
  describe 'update_site_syslog_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
