=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rapid7VmConsole::DiscoverySearchCriteria
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DiscoverySearchCriteria' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::DiscoverySearchCriteria.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DiscoverySearchCriteria' do
    it 'should create an instance of DiscoverySearchCriteria' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::DiscoverySearchCriteria)
    end
  end
  describe 'test attribute "connection_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["activesync-ldap", "activesync-office365", "activesync-powershell", "aws", "dhcp", "sonar", "vsphere"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.connection_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "filters"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "match"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["any", "all"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.match = value }.not_to raise_error
       #end
    end
  end

end

