=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rapid7VmConsole::RangeResource
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RangeResource' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::RangeResource.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RangeResource' do
    it 'should create an instance of RangeResource' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::RangeResource)
    end
  end
  describe 'test attribute "every"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["day", "month", "year"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.every = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["P1Y", "P6M", "P3M", "P1M", "<date>"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.from = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "interval"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

