=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rapid7VmConsole::RiskTrendResource
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RiskTrendResource' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::RiskTrendResource.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RiskTrendResource' do
    it 'should create an instance of RiskTrendResource' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::RiskTrendResource)
    end
  end
  describe 'test attribute "all_assets"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "asset_group_membership"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["historical", "generation"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.asset_group_membership = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "asset_groups"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["average", "total"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.asset_groups = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "assets"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["P1Y", "P6M", "P3M", "P1M", "<date>"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.from = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "sites"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["average", "total"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.sites = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "tag_membership"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["historical", "generation"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.tag_membership = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "tags"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["average", "total"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.tags = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

