=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rapid7VmConsole::RiskTrendAllAssetsResource
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RiskTrendAllAssetsResource' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::RiskTrendAllAssetsResource.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RiskTrendAllAssetsResource' do
    it 'should create an instance of RiskTrendAllAssetsResource' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::RiskTrendAllAssetsResource)
    end
  end
  describe 'test attribute "total"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "trend"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["average-risk", "number-of-assets", "none"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.trend = value }.not_to raise_error
       #end
    end
  end

end

