=begin
Ruby InsightVM API Client

OpenAPI spec version: 3
Contact: support@rapid7.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rapid7VmConsole::WebPage
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebPage' do
  before do
    # run before each test
    @instance = Rapid7VmConsole::WebPage.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebPage' do
    it 'should create an instance of WebPage' do
      expect(@instance).to be_instance_of(Rapid7VmConsole::WebPage)
    end
  end
  describe 'test attribute "link_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["seed", "html-ref", "robots", "js-string", "query-param", "pdf", "css", "implied-dir", "rss", "redirection", "sitemap", "backup", "vck-rewrite", "non-ref-guess", "soft-404"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.link_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "path"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "response"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

